// import { getCookies } from "cookies-next";

export default {
  USER: "/user",
  FAS_LOGIN: "/user/login",
  FAS_SIGNUP: "/user/register",
  FAS_MYBACKGROUND: "/user/background-images",
  FAS_NOTIFICATION: "/user/notifications",
  FAS_WISHLIST: "/my-wishlist",
  FAS_UPDATE_PASSWORD: "/user/change-password",
  FAS_CART: "/cart",
  FAS_ADD_TO_CART: "/apparel/add-to-cart",
  FAS_FRIEND_REQUEST: "/user/friend-requests",
  // MY_FRIEND: `/user`,
  FAS_SENT_FRIEND_REQUEST: "/user/sent-friend-requests",
  FAS_CANCEL_FRIEND_REQUEST: "/user/cancel-friend-request",
  FAS_ACCEPT_FRIEND_REQUEST: "/user/accept-friend-request",
  FAS_REMOVE_FRIEND: "/user/remove-friend",
  FAS_HOME_LATEST: "/user/feeds",
  FAS_HOME_FOLLOWING: "/user/feeds",
  FAS_APPARELS: "/user/apparels",
  SEARCH_FRIEND: "/user/search-friends",
  FAS_FOLLOWERS: "/user/3/followers",
  FAS_FOLLOWING: "/user/3/followings",
  FAS_CHANGE_SETTINGS: "/user/change-settings",
  FAS_ADD_TO_WISHLIST: "/user/add-to-wishlist",
  FAS_UPLOAD_IMG: "/user/upload-image",
  FAS_USER_SUGGESTIONS: "/user/suggestions",
  FAS_MAIN_SEARCH: "/user/autocomplete",
  FAS_LOGOUT: "/user/logout",
  FAS_MARK_AS_READ: "/user/mark-as-read",
  FORGETPASSWORD: "/user/forgot-password",
  FAS_VERIFYMAIL: "/user/verify-email",
  FAS_FEED_LIKE: "/user/like-feed",
  FAS_ADD_FRIENDS: "/user/add-friend",
  FAS_DELETE_NOTIFICATION: "/user/notifications",
  FAS_ADD_APPAREL: "/user/add-apparels",
  FAS_UNREAD_COUNT: "/user/unread-count",
  FAS_SEND_OTP: "/user/send-otp",
  FAS_VERIFY_MOBILE: "/user/verify-mobile-number",
  USER_2: "/users/2",
  // FAS_MY_WARDROBE: ""
};
