export default {
  HOME: "/home",
  WISHLIST: "/wishlist",
  CARTS: "/carts",
  FAS_CHANGE_PASSWORD: "/fashioninsta/changepassword",
  FAS_MY_PROFILE: "/fashioninsta/myprofile",
  RET_MY_PROFILE: "/retailer/myprofile",
  TERMS_AND_CONDITIONS: "/fashioninsta/termsandconditions",
  PRIVACY_POLICY: "/fashioninsta/privacypolicy",
  FAS_ADD_APPAREL: "/fashioninsta/addapparel",
  LANDING_PAGE: "/",
  OTHER_USTER_PROFILE: "/fashioninsta/mywardrobe/otheruserprofile",
  HOME_LATEST_DETAIL: "home/homelatestdetail",
  HOME_FOLLOWING_DETAIL: "home/homefollowingDetail",
  WARDROBE_LOOKBOOK_DETAIL: "mywardrobe/lookdetail",
  WISHLIST_DETAIL: "wishlist/wishlistdetail",
  LOGIN: "/login",
  SUGGESTED_PEOPLE: "/fashioninsta/suggestedpeoples",
  SUGGESTED_RETAILER: "/fashioninsta/suggestedretailer",
  SUGGESTED_APPAREL: "/fashioninsta/suggestedapparels",
};
